#!/bin/bash

# WARNING: DO NOT EDIT!
#
# This file was generated by plugin_template, and is managed by it. Please use
# './plugin-template --github pulpcore' to update this file.
#
# For more info visit https://github.com/pulp/plugin_template

set -euv

# make sure this script runs at the repo root
cd "$(dirname "$(realpath -e "$0")")"/../../..

pip install twine

export response=$(curl --write-out %{http_code} --silent --output /dev/null https://pypi.org/project/pulpcore-client/$1/)

if [ "$response" == "200" ];
then
  echo "pulpcore client $1 has already been released. Skipping."
  exit
fi

twine check dist/pulpcore-client-$1.tar.gz || exit 1
twine check dist/pulpcore_client-$1-py3-none-any.whl || exit 1
twine upload dist/pulpcore-client-$1.tar.gz -u pulp -p $PYPI_PASSWORD
twine upload dist/pulpcore_client-$1-py3-none-any.whl -u pulp -p $PYPI_PASSWORD

exit $?
